Repository FFFabulousRobotics/FTC-2024-2025, pull requests merged in 2024-09, with the labels that each got.

#1 Brand new Task design
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/ManualOpMode.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OneTimeTask.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/SleepTask.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Task.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TaskOpMode.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TaskStatus.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TimedServo.java
Labels: enhancement

#2 Task system update
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/OneTimeTask.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/Task.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TaskOpMode.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TaskStatus.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/hardware/TimedServo.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/task/OneTimeTask.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/task/SleepTask.java
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/task/Task.java
Labels: documentation, enhancement

#4 Change Android CI run setting
  .github/workflows/android.yml
Labels: bug

#5 Fix: solve the warnings
  TeamCode/src/main/java/org/firstinspires/ftc/teamcode/TaskOpMode.java
Labels: bug
